/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package atvdparcial;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

public class main_interface extends javax.swing.JFrame {

    /**
     * Creates new form main_interface
     */
    public main_interface() {
        initComponents();
        listarProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtb_Novo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtb_Up = new javax.swing.JButton();
        bt_del = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        txt_id = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_desc = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jtb_Novo.setText("Novo");
        jtb_Novo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_NovoMouseClicked(evt);
            }
        });
        jtb_Novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_NovoActionPerformed(evt);
            }
        });

        jLabel1.setText("nome:");

        txt_nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Descricao:");

        jtb_Up.setText("Atualizar");
        jtb_Up.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtb_UpMouseClicked(evt);
            }
        });
        jtb_Up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtb_UpActionPerformed(evt);
            }
        });

        bt_del.setText("Excluir");
        bt_del.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_delMouseClicked(evt);
            }
        });

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6"
            }
        ));
        jScrollPane2.setViewportView(tab);

        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        jLabel2.setText("ID:");

        txt_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_desc)
                            .addComponent(txt_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))
                        .addGap(57, 57, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(29, 29, 29))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jtb_Novo)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtb_Up, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_id))
                        .addGap(18, 18, 18)
                        .addComponent(bt_del))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtb_Novo)
                    .addComponent(jtb_Up)
                    .addComponent(bt_del)
                    .addComponent(txt_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtb_NovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_NovoMouseClicked
    
    inserirProduto();
    listarProduto();
    }//GEN-LAST:event_jtb_NovoMouseClicked

    private void txt_nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeActionPerformed

    private void jtb_UpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_UpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_UpActionPerformed

    private void jtb_UpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtb_UpMouseClicked
        
        try {
            upProduto();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        listarProduto();
    }//GEN-LAST:event_jtb_UpMouseClicked

    private void jtb_NovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtb_NovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtb_NovoActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void bt_delMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_delMouseClicked
    
        try {
            delProduto();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main_interface.class.getName()).log(Level.SEVERE, null, ex);
        }
        listarProduto();
    }//GEN-LAST:event_bt_delMouseClicked

    private void txt_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main_interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main_interface().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_del;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jtb_Novo;
    private javax.swing.JButton jtb_Up;
    private javax.swing.JTable tab;
    private javax.swing.JTextField txt_desc;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextField txt_nome;
    // End of variables declaration//GEN-END:variables

    private void listarProduto(){
        try{
            ProdutoDAO objprodutodao = new ProdutoDAO();
            
            DefaultTableModel model = (DefaultTableModel) tab.getModel();
            model.setNumRows(0);
            
            ArrayList<ProdutoDTO> lista = objprodutodao.PesquisarProduto();
            
            for(int num = 0; num < lista.size(); num ++){
                model.addRow(new Object[]{
                    lista.get(num).getId_Produto(),
                    lista.get(num).getNome_Produto(),
                    lista.get(num).getDescricao_Produto()
                    
                });
            }
        }catch(Exception erro){
            JOptionPane.showMessageDialog(null,"Erro ao listar dados"+ erro.getMessage());
        }
    }
    
    private void inserirProduto(){
            try {
                
            String nome;
            String descricao;
            
            nome = txt_nome.getText();
            descricao = txt_desc.getText();
            
            
            ProdutoDTO objprodutodto = new ProdutoDTO();
            
            objprodutodto.setNome_Produto(nome);
            objprodutodto.setDescricao_Produto(descricao);
            
           
            ProdutoDAO objprodutodao = new ProdutoDAO();
            objprodutodao.novoDesc(objprodutodto);
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(main_interface.class.getName()).log(Level.SEVERE, null, ex);
           }
        listarProduto();
     }
    
    private void upProduto() throws ClassNotFoundException{
        
        int id;
        String nome;
        String descricao;
        
        id = Integer.parseInt(txt_id.getText());
        nome = txt_nome.getText();
        descricao = txt_desc.getText();
        
        ProdutoDTO objprodutodto = new ProdutoDTO();
        objprodutodto.setId_Produto(id);
        objprodutodto.setNome_Produto(nome);
        objprodutodto.setDescricao_Produto(descricao);
                
        ProdutoDAO objprodutodao = new ProdutoDAO();
        objprodutodao.upDesc(objprodutodto);
        
        
    }
    
    private void delProduto() throws ClassNotFoundException{
        int id;
        id = Integer.parseInt(txt_id.getText());
        
        ProdutoDTO objprodutodto = new ProdutoDTO();
        objprodutodto.setId_Produto(id);
        
        ProdutoDAO objprodutodao = new ProdutoDAO();
        objprodutodao.deleteDesc(objprodutodto);
        
    }
    
}
